### ISSUE TITLE
Follow official style Guide

### ISSUE THREAD

**Issue by aparcar** [mwarning/yet_another_firmware_selector#3]
As this wizard uses the official firmware images we should ask to offer it on the main website in the downloads area. For that we should follow the official style guide [here](https://openwrt.org/docs/guide-graphic-designer/openwrt-logo)

**Comment by mwarning** [comment]
Here is some OpenWrt branding: https://mwarning.de/yet_another_firmware_selector/
I do not like it. But might do for now.

**Comment by aparcar** [comment]
Where can I find the soruce?

**Comment by mwarning** [comment]
I've just pushed it here: https://github.com/mwarning/yet_another_firmware_selector/tree/openwrt_theme
