### ISSUE TITLE
Link only current download-files

### ISSUE THREAD

**Issue by FreifunkUFO** [mwarning/yet_another_firmware_selector#39]
when i build firmware several times in the same browser-window (with different additional packages) i get more and more download-icons. 
see screenshot, only the two files in the center can be downloaded

**Comment by FreifunkUFO** [comment]
![yast-fehler](https://user-images.githubusercontent.com/2579265/84166429-28c33a00-aa75-11ea-9d36-e3b707c00c4c.png)

screenshot firefox

**Comment by mwarning** [comment]
hi FreifunkUFO,

we would need to find out if:

1. this is a bug in the collect.py script
  - how to you call the collect.py script?
2. this is a bug in the openwrt generation of the JSON metadata
  -  can you check if the json files in the image folder have duplicated entries?

**Comment by FreifunkUFO** [comment]
i am using firefox on https://chef.libremesh.org

the bug can be seen also from other computers. just open it, choose 902acv1 and write some package into "customize". you should now see two more download-icons then me.

maybe files are useful (all 902acv1-generated files) but are not named. (i am also missing the build-log to have a view)

![yast-fehler2](https://user-images.githubusercontent.com/2579265/84168833-2a423180-aa78-11ea-83b3-a184062ad98b.png)

**Comment by mwarning** [comment]
hm, it works for me (Firefox 75.0). What browser version do you use?

**Comment by mwarning** [comment]
nvm., I saw the same. Not sure how I did it..

**Comment by mwarning** [comment]
Ok, this is the build server sending information of a bunch of images.
@aparcar I think you need to fix your build server.

**Comment by aparcar** [comment]
Yes I found this problem too and here is the solution. https://github.com/openwrt/openwrt/pull/3091

**Comment by mwarning** [comment]
Closing this issue here, as this is not a yafs bug.

**Comment by mwarning** [comment]
thanks @FreifunkUFO for reporting!
