### ISSUE TITLE
luci support

### ISSUE THREAD

**Issue by FreifunkUFO** [mwarning/yet_another_firmware_selector#42]
would be nice to have this project in luci
it is only html and js, so it should be possible.

but the misc-directory (incl. python) has to be changed first
https://github.com/mwarning/yet_another_firmware_selector/issues/41

**Comment by FreifunkUFO** [comment]
a bit like https://github.com/openwrt/luci/tree/master/applications/luci-app-attendedsysupgrade , but also for build other-devices images or images for that device, but with different settings (f.i. packages or config or files)

**Comment by mwarning** [comment]
I do not understand how the misc folder is a problem, because YAFS as LuCI module would be a new project that has different folders etc. anyway.

**Comment by mwarning** [comment]
There is the luci-app-attendedsysupgrade (ASU) package. That should do it.
