### ISSUE TITLE
Show build-log of custom images

### ISSUE THREAD

**Issue by FreifunkUFO** [mwarning/yet_another_firmware_selector#43]
a possibility to have a look at the build-log would be important.
ASU is supporting that already

**Comment by FreifunkUFO** [comment]
see also https://github.com/mwarning/yet_another_firmware_selector/issues/15

**Comment by mwarning** [comment]
The build log is already linked to in case of build errors.

@aparcar iirc, you did not want to have it shown in case of a successful build?

**Comment by aparcar** [comment]
I'm fine with showing them on every build

**Comment by mwarning** [comment]
fixed in #46
