### ISSUE TITLE
usage for libremesh / chef

### ISSUE THREAD

**Issue by FreifunkUFO** [mwarning/yet_another_firmware_selector#44]
atm this project was claimed to be the official chef.libremesh.org, the successor of the former chef (https://github.com/libremesh/chef/) which had more features than this project atm.

please provide readme, documentation oder hints:
* how to create images for libremesh
* how to change package-list, flavors, network-config and local settings

**Comment by mwarning** [comment]
> atm this project was claimed to be the official chef.libremesh.org, the successor of the former chef (https://github.com/libremesh/chef/) which had more features than this project atm.

I think there is a misunderstanding. ASU support was added to support libremesh/chef, but I need YAFS for Freifunk projects I am involved in. They do not use libremesh or gluon and the other firmware selectors available have a hard dependency on Gluon.

> 
> please provide readme, documentation oder hints:
> 
>     * how to create images for libremesh
This topic feels to be too far removed from this project...
> 
>     * how to change package-list, flavors, network-config and local settings
This should be documented in the ASU project, as it is their API.
YAFS should link to that.

**Comment by FreifunkUFO** [comment]
ok i will ask libremesh people
